"""
AI Equity Research Assistant — Dashboard Edition
--------------------------------------------------
A dashboard-style Streamlit app for equity research: sidebar navigation,
card-based key metrics, revenue trend chart, and a rule-based summary.

Setup (run once in your terminal):
    pip install streamlit streamlit-option-menu yfinance pandas

Run:
    streamlit run streamlit_app.py

DISCLAIMER: This is a student/academic project for learning purposes only.
It is NOT real investment advice, and the "Summary" / "Insights" text below
is generated by simple rule-based logic on financial ratios — not a real AI
model reading the news or filings. The recommendation logic is a simplified
scoring system, not a professional research process.
"""

import streamlit as st
import yfinance as yf
import pandas as pd

try:
    from streamlit_option_menu import option_menu
    HAS_OPTION_MENU = True
except ImportError:
    HAS_OPTION_MENU = False

st.set_page_config(page_title="AI Equity Research Assistant", page_icon="📊", layout="wide")

# ---------------------------------------------------------------------
# STYLING
# ---------------------------------------------------------------------
st.markdown(
    """
    <style>
    .stApp {
        background: linear-gradient(180deg, #0a0e17 0%, #0d1220 100%);
    }
    div[data-testid="stMetric"] {
        background-color: rgba(255, 255, 255, 0.04);
        border: 1px solid rgba(255, 255, 255, 0.08);
        border-radius: 12px;
        padding: 14px 16px;
    }
    section[data-testid="stSidebar"] {
        background-color: #0d1220;
        border-right: 1px solid rgba(255,255,255,0.06);
    }
    .card {
        background-color: rgba(255, 255, 255, 0.04);
        border: 1px solid rgba(255, 255, 255, 0.08);
        border-radius: 14px;
        padding: 20px;
        margin-bottom: 16px;
    }
    .badge-good { color: #3ddc84; font-size: 13px; }
    .badge-warn { color: #f5b942; font-size: 13px; }
    .badge-bad  { color: #ff6b6b; font-size: 13px; }
    .header-title { font-size: 26px; font-weight: 700; color: #ffffff; }
    .header-sub { color: #8a94a6; font-size: 14px; }
    </style>
    """,
    unsafe_allow_html=True,
)

# ---------------------------------------------------------------------
# DATA FUNCTIONS
# ---------------------------------------------------------------------
def get_key_ratios(info):
    return {
        "P/E (trailing)": info.get("trailingPE"),
        "P/E (forward)": info.get("forwardPE"),
        "P/B": info.get("priceToBook"),
        "ROE": info.get("returnOnEquity"),
        "ROA": info.get("returnOnAssets"),
        "Debt/Equity": info.get("debtToEquity"),
        "Net Profit Margin": info.get("profitMargins"),
        "Revenue Growth (YoY)": info.get("revenueGrowth"),
        "Earnings Growth (YoY)": info.get("earningsGrowth"),
        "Dividend Yield": info.get("dividendYield"),
    }


def get_stock_status(ticker_obj, info):
    hist = ticker_obj.history(period="5y")
    current_price = info.get("currentPrice") or (hist["Close"].iloc[-1] if not hist.empty else None)
    ma200 = hist["Close"].rolling(200).mean().iloc[-1] if len(hist) >= 200 else None
    return {
        "current_price": current_price,
        "week52_high": info.get("fiftyTwoWeekHigh"),
        "week52_low": info.get("fiftyTwoWeekLow"),
        "ma200": ma200,
    }, hist


def generate_recommendation(ratios, stock_status):
    score = 0
    reasons = []

    roe = ratios.get("ROE")
    if roe is not None:
        if roe > 0.15:
            score += 1; reasons.append(("good", f"Strong ROE of {roe*100:.1f}% (healthy profitability)"))
        elif roe < 0.05:
            score -= 1; reasons.append(("bad", f"Weak ROE of {roe*100:.1f}%"))

    rev_growth = ratios.get("Revenue Growth (YoY)")
    if rev_growth is not None:
        if rev_growth > 0.10:
            score += 1; reasons.append(("good", f"Solid revenue growth of {rev_growth*100:.1f}% YoY"))
        elif rev_growth < 0:
            score -= 1; reasons.append(("bad", f"Revenue declining ({rev_growth*100:.1f}% YoY)"))

    de = ratios.get("Debt/Equity")
    if de is not None:
        if de > 150:
            score -= 1; reasons.append(("bad", f"High Debt/Equity of {de:.1f} (leverage risk)"))
        elif de < 50:
            score += 1; reasons.append(("good", f"Low Debt/Equity of {de:.1f} (conservative balance sheet)"))
        else:
            reasons.append(("warn", f"Moderate Debt/Equity of {de:.1f}"))

    pe = ratios.get("P/E (trailing)")
    if pe is not None:
        if pe < 15:
            score += 1; reasons.append(("good", f"Attractive valuation, P/E of {pe:.1f}"))
        elif pe > 40:
            score -= 1; reasons.append(("bad", f"Expensive valuation, P/E of {pe:.1f}"))

    price = stock_status.get("current_price")
    ma200 = stock_status.get("ma200")
    if price and ma200 and not pd.isna(ma200):
        if price > ma200:
            score += 1; reasons.append(("good", "Price trading above 200-day average (positive trend)"))
        else:
            score -= 1; reasons.append(("bad", "Price trading below 200-day average (negative trend)"))

    if score >= 2:
        call, color = "BUY", "#3ddc84"
    elif score <= -2:
        call, color = "SELL", "#ff6b6b"
    else:
        call, color = "HOLD", "#f5b942"

    star_rating = min(5.0, max(1.0, 3 + score * 0.5))
    return call, color, score, reasons, star_rating


def badge_class(kind):
    return {"good": "badge-good", "warn": "badge-warn", "bad": "badge-bad"}.get(kind, "badge-warn")


def ratio_badge(label, value):
    """Return a simple text badge (Excellent/Good/Moderate/Weak) for common ratios."""
    if value is None:
        return "N/A", "warn"
    if label == "ROE":
        if value > 0.20: return "Excellent", "good"
        if value > 0.12: return "Good", "good"
        if value > 0.05: return "Moderate", "warn"
        return "Weak", "bad"
    if label == "Debt/Equity":
        if value < 50: return "Healthy", "good"
        if value < 150: return "Moderate", "warn"
        return "High", "bad"
    if label == "Net Profit Margin":
        if value > 0.15: return "Excellent", "good"
        if value > 0.08: return "Good", "good"
        if value > 0: return "Thin", "warn"
        return "Negative", "bad"
    return "", "warn"


# ---------------------------------------------------------------------
# SIDEBAR NAVIGATION
# ---------------------------------------------------------------------
PAGES = ["Dashboard", "Financial Ratios", "Financial Statements", "Charts", "Risk Analysis", "About"]

with st.sidebar:
    st.markdown("### 📊 AI Equity Research Assistant")
    if HAS_OPTION_MENU:
        selected_page = option_menu(
            menu_title=None,
            options=PAGES,
            icons=["speedometer2", "bar-chart", "file-earmark-text", "graph-up", "shield-exclamation", "info-circle"],
            default_index=0,
        )
    else:
        selected_page = st.radio("Navigate", PAGES, label_visibility="collapsed")

    st.divider()
    ticker_symbol = st.text_input("Ticker", value="BAJFINANCE.NS", help="e.g. BAJFINANCE.NS, TCS.NS, INFY.NS")
    analyze_clicked = st.button("Analyze", type="primary", width="stretch")
    st.divider()
    st.caption("Educational/academic project only. Not investment advice.")

# persist last analyzed ticker across page nav clicks
if "ticker" not in st.session_state:
    st.session_state.ticker = None
if analyze_clicked:
    st.session_state.ticker = ticker_symbol

# ---------------------------------------------------------------------
# MAIN CONTENT
# ---------------------------------------------------------------------
if not st.session_state.ticker:
    st.title("📊 AI Equity Research Assistant")
    st.write("Enter a ticker in the sidebar and click **Analyze** to get started.")
else:
    with st.spinner(f"Fetching data for {st.session_state.ticker}..."):
        try:
            ticker_obj = yf.Ticker(st.session_state.ticker)
            info = ticker_obj.info
        except Exception as e:
            st.error(f"Something went wrong: {e}")
            info = None

    if not info or info.get("longName") is None:
        st.error("Could not find data for this ticker. Double-check the symbol (e.g. add .NS for NSE stocks).")
    else:
        ratios = get_key_ratios(info)
        stock_status, hist = get_stock_status(ticker_obj, info)
        call, color, score, reasons, stars = generate_recommendation(ratios, stock_status)

        # --- Header row ---
        h1, h2 = st.columns([3, 1])
        with h1:
            st.markdown(f'<div class="header-title">{info.get("longName","N/A")}</div>', unsafe_allow_html=True)
            st.markdown(
                f'<div class="header-sub">{st.session_state.ticker} · {info.get("sector","N/A")} · {info.get("industry","N/A")}</div>',
                unsafe_allow_html=True,
            )
        with h2:
            st.markdown(
                f'<div style="text-align:right; font-size:24px; font-weight:700; color:{color};">{call}</div>',
                unsafe_allow_html=True,
            )
            st.markdown(f'<div style="text-align:right;">{"⭐" * int(round(stars))} {stars:.1f}/5</div>', unsafe_allow_html=True)

        st.divider()

        if selected_page == "Dashboard":
            price = stock_status["current_price"]
            c1, c2, c3 = st.columns(3)
            c1.metric("Current Price", f"₹{price:,.2f}" if price else "N/A")
            c2.metric("52-Week High", f"₹{stock_status['week52_high']:,.2f}" if stock_status["week52_high"] else "N/A")
            c3.metric("52-Week Low", f"₹{stock_status['week52_low']:,.2f}" if stock_status["week52_low"] else "N/A")

            st.subheader("Key Financials")
            k1, k2, k3, k4 = st.columns(4)
            roe = ratios.get("ROE")
            de = ratios.get("Debt/Equity")
            npm = ratios.get("Net Profit Margin")
            pe = ratios.get("P/E (trailing)")

            with k1:
                b, kind = ratio_badge("ROE", roe)
                st.metric("ROE", f"{roe*100:.2f}%" if roe is not None else "N/A")
                st.markdown(f'<span class="{badge_class(kind)}">{b}</span>', unsafe_allow_html=True)
            with k2:
                b, kind = ratio_badge("Debt/Equity", de)
                st.metric("Debt/Equity", f"{de:.2f}" if de is not None else "N/A")
                st.markdown(f'<span class="{badge_class(kind)}">{b}</span>', unsafe_allow_html=True)
            with k3:
                b, kind = ratio_badge("Net Profit Margin", npm)
                st.metric("Net Profit Margin", f"{npm*100:.2f}%" if npm is not None else "N/A")
                st.markdown(f'<span class="{badge_class(kind)}">{b}</span>', unsafe_allow_html=True)
            with k4:
                st.metric("P/E (trailing)", f"{pe:.2f}" if pe is not None else "N/A")

            st.write("")
            col_chart, col_summary = st.columns([2, 1])
            with col_chart:
                st.markdown('<div class="card">', unsafe_allow_html=True)
                st.markdown("**Price Trend (5Y)**")
                if not hist.empty:
                    st.line_chart(hist["Close"], height=260)
                else:
                    st.write("No price history available.")
                st.markdown('</div>', unsafe_allow_html=True)

            with col_summary:
                st.markdown('<div class="card">', unsafe_allow_html=True)
                st.markdown("**Summary**")
                good_pts = [r for k, r in reasons if k == "good"]
                bad_pts = [r for k, r in reasons if k == "bad"]
                summary_bits = []
                if good_pts:
                    summary_bits.append("Strengths: " + "; ".join(good_pts[:2]) + ".")
                if bad_pts:
                    summary_bits.append("Watch-outs: " + "; ".join(bad_pts[:2]) + ".")
                st.write(" ".join(summary_bits) if summary_bits else "Not enough data to summarize.")
                st.caption("Generated by rule-based scoring, not a language model.")
                st.markdown('</div>', unsafe_allow_html=True)

            with st.expander("📖 Business Summary / History"):
                st.write(info.get("longBusinessSummary", "No summary available."))

        elif selected_page == "Financial Ratios":
            st.subheader("📐 Key Financial Ratios")
            ratio_cols = st.columns(5)
            for i, (k, v) in enumerate(ratios.items()):
                with ratio_cols[i % 5]:
                    if v is None:
                        st.metric(k, "N/A")
                    elif any(x in k for x in ["Margin", "Growth", "ROE", "ROA", "Yield"]):
                        st.metric(k, f"{v*100:.2f}%")
                    else:
                        st.metric(k, f"{v:.2f}")

        elif selected_page == "Financial Statements":
            st.subheader("📑 Financial Statements")
            tab1, tab2, tab3 = st.tabs(["Income Statement", "Balance Sheet", "Cash Flow"])
            with tab1:
                try:
                    st.dataframe(ticker_obj.financials, width="stretch")
                except Exception:
                    st.write("Not available.")
            with tab2:
                try:
                    st.dataframe(ticker_obj.balance_sheet, width="stretch")
                except Exception:
                    st.write("Not available.")
            with tab3:
                try:
                    st.dataframe(ticker_obj.cashflow, width="stretch")
                except Exception:
                    st.write("Not available.")

        elif selected_page == "Charts":
            st.subheader("📈 Price Charts")
            period = st.select_slider("Period", options=["6mo", "1y", "2y", "5y"], value="1y")
            chart_hist = ticker_obj.history(period=period)
            if not chart_hist.empty:
                st.line_chart(chart_hist["Close"], height=400)
                st.line_chart(chart_hist["Volume"], height=200)
            else:
                st.write("No data available for this period.")

        elif selected_page == "Risk Analysis":
            st.subheader("⚠️ Risk Analysis")
            for kind, text in reasons:
                icon = "✅" if kind == "good" else ("⚠️" if kind == "warn" else "🔴")
                st.write(f"{icon} {text}")
            st.info("Disclaimer: Educational/academic project only. Not investment advice.")

        elif selected_page == "About":
            st.subheader("About this project")
            st.write(
                "This tool pulls live financial data for any listed stock and generates a "
                "rule-based BUY / HOLD / SELL call using fundamentals, valuation, and price trend."
            )
            st.write(
                "**Note:** the 'Summary' and star rating are produced by simple rule-based "
                "logic on financial ratios — not a real AI model analyzing news or filings."
            )

st.divider()
st.caption("Built with Python & Streamlit")
